---
core:
  num_workers: 50  #Upper boundary on the maximum number of concurrent jobs

inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "inventory/hosts.yaml"
    group_file: "inventory/groups.yaml"
    defaults_file: "inventory/defaults.yaml"